// Generated by CoffeeScript 1.3.3

/*
# UVEPE8 Player
# Author:       Felipe "Pyron" Martín (@fmartingr)
# Notes:		    See README
*/


(function() {
  var uvepe8;

  uvepe8 = function(dom_object, animation, autostart) {
    var options;
    options = {
      dom: "",
      width: "",
      height: "",
      frames: "",
      image: "",
      fps: ""
    };
    if (!(this instanceof uvepe8)) {
      return new uvepe8(dom_object, animation, autostart);
    } else {
      return this.init(dom_object, animation, autostart);
    }
  };

  uvepe8.prototype = {
    foo: function() {
      return true;
    },
    find_framework: function() {
      if ((typeof jQuery !== "undefined" && jQuery !== null) || (typeof Zepto !== "undefined" && Zepto !== null)) {
        this.framework = $;
      }
      if (typeof Quo !== "undefined" && Quo !== null) {
        this.framework = $$;
      }
      if (!(this.framework != null)) {
        throw "[Can't found compatible framwork. Please include Zepto, jQuery or QuoJS.]";
      }
      return true;
    },
    canvas_supported: function() {
      var element;
      element = this.create_canvas();
      return !!(element.getContext() && element.getContext('2d'));
    },
    draw_canvas: function() {
      var destiny_x, destiny_y, diff, empty_array, frame, height, source_x, source_y, width, _i, _len, _ref;
      empty_array = [];
      console.log("Draw frame " + this.current_frame);
      frame = this.get_frame(this.current_frame);
      if (frame !== null) {
        if (frame.diff.length > 0) {
          _ref = frame.diff;
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            diff = _ref[_i];
            console.log(diff);
            source_x = diff[2];
            source_y = diff[3];
            width = diff[4];
            height = diff[5];
            destiny_x = diff[0];
            destiny_y = diff[1];
            this.buffer_context.clearRect(destiny_x, destiny_y, width, height);
            this.buffer_context.drawImage(this.image, source_x, source_y, width, height, destiny_x, destiny_y, width, height);
          }
          this.dom_context.clearRect(0, 0, this.options.width, this.options.height);
          return this.dom_context.drawImage(this.buffer_element, 0, 0);
        }
      }
    },
    draw_fallback: function() {
      return console.log('fallback');
    },
    get_frame: function(number) {
      if (this.options.frames[number] != null) {
        return this.options.frames[number];
      } else {
        return null;
      }
    },
    draw: function() {
      var frame, timeout,
        _this = this;
      frame = this.get_frame(this.current_frame);
      if (frame !== null) {
        timeout = this.options.timeout;
        if (frame.jump != null) {
          timeout = timeout * frame.jump;
        }
        console.log("Frame: " + this.current_frame + " with timeout: " + timeout);
        setTimeout(function() {
          return _this.draw();
        }, timeout);
        if (this.use_canvas) {
          this.draw_canvas();
        } else {
          this.draw_fallback();
        }
        return this.current_frame++;
      }
    },
    play: function() {
      return this.draw();
    },
    create_canvas: function() {
      return document.createElement('canvas');
    },
    start_canvas: function() {
      this.dom_canvas = this.create_canvas();
      this.dom_canvas.width = this.options.width;
      this.dom_canvas.height = this.options.height;
      this.dom_context = this.dom_canvas.getContext('2d');
      this.dom.append(this.dom_canvas);
      this.buffer_element = this.create_canvas();
      this.buffer_element.width = this.options.width;
      this.buffer_element.height = this.options.height;
      return this.buffer_context = this.buffer_element.getContext('2d');
    },
    init: function(dom_object, animation, autostart) {
      if (autostart == null) {
        autostart = true;
      }
      if (animation != null) {
        this.options = animation;
      }
      if (dom_object != null) {
        this.options.dom = dom_object;
      }
      if (this.find_framework()) {
        this.use_canvas = true;
        this.current_frame = 0;
        this.dom = this.framework(this.options.dom);
        this.options.timeout = 1000 / this.options.fps;
        this.image = new Image();
        this.image.src = this.options.image;
        this.dom.css({
          width: this.options.width,
          height: this.options.height
        }, this.use_canvas ? this.start_canvas() : void 0);
        if (autostart) {
          this.play();
        }
      }
      return this;
    }
  };

  window.uvepe8 = uvepe8;

}).call(this);
